apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: cluster-01
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: cluster-01-controlplane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: GCPCluster
    name: cluster-01
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPCluster
metadata:
  name: cluster-01
  namespace: default
spec:
  network:
    name: default
  project: hackathon-2022-352503
  region: australia-southeast1
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: cluster-01-controlplane
  namespace: default
spec:
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: v1.0.5
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: GCPMachineTemplate
    name: cluster-01-controlplane
  replicas: 1
  version: v1.24.0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPMachineTemplate
metadata:
  name: cluster-01-controlplane
  namespace: default
spec:
  template:
    spec:
      image: projects/hackathon-2022-352503/global/images/talos
      instanceType: n1-standard-2
      publicIP: true
      rootDeviceSize: 50
      serviceAccounts: {}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: cluster-01-workers
  namespace: default
spec:
  clusterName: cluster-01
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
          name: cluster-01-workers
      clusterName: cluster-01
      failureDomain: australia-southeast1-a
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: GCPMachineTemplate
        name: cluster-01-workers
      version: 1.24.0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: GCPMachineTemplate
metadata:
  name: cluster-01-workers
  namespace: default
spec:
  template:
    spec:
      image: projects/hackathon-2022-352503/global/images/talos
      instanceType: n1-standard-2
      publicIP: true
      rootDeviceSize: 50
      serviceAccounts: {}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: cluster-01-workers
  namespace: default
spec:
  template:
    spec:
      generateType: join
      talosVersion: v1.0.5
